import { readFile, writeFile } from 'node:fs/promises';
import { DocxPackage } from '../src/package/docx';
import { child, isWord, patchXml, W } from '../src/package/xml';

// Deliberate synthetic variants of a docxfix document. Keep this independent
// of the numbering resolver: fixtures must not be generated by the code tested.
const path = 'fixtures/generated/lists.docx';
const pkg = DocxPackage.open(await readFile(path));
const levels = (bullet = false) =>
  [0, 1, 2]
    .map(
      (i) =>
        `<w:lvl w:ilvl="${i}"><w:start w:val="1"/><w:numFmt w:val="${bullet ? 'bullet' : 'decimal'}"/><w:lvlText w:val="${bullet ? ['•', '◦', '▪'][i] : ['%1.', '%1.%2.', '%1.%2.%3.'][i]}"/><w:lvlJc w:val="left"/><w:pPr><w:ind w:left="${(i + 1) * 720}" w:hanging="360"/></w:pPr></w:lvl>`,
    )
    .join('');
const numbering = `<w:numbering xmlns:w="${W}">
  <w:abstractNum w:abstractNumId="0">${levels()}</w:abstractNum>
  <w:abstractNum w:abstractNumId="1">${levels(true)}</w:abstractNum>
  <w:abstractNum w:abstractNumId="4"><w:nsid w:val="76543210"/>${levels()}</w:abstractNum>
  <w:abstractNum w:abstractNumId="2"><w:lvl w:ilvl="0"><w:start w:val="27"/><w:numFmt w:val="upperLetter"/><w:lvlText w:val="%1)"/><w:pPr><w:ind w:left="720" w:hanging="360"/></w:pPr></w:lvl></w:abstractNum>
  <w:abstractNum w:abstractNumId="3"><w:lvl w:ilvl="0"><w:start w:val="4"/><w:numFmt w:val="upperRoman"/><w:lvlText w:val="%1."/><w:pPr><w:ind w:left="720" w:hanging="360"/></w:pPr></w:lvl></w:abstractNum>
  <w:num w:numId="1"><w:abstractNumId w:val="0"/></w:num>
  <w:num w:numId="2"><w:abstractNumId w:val="1"/></w:num>
  <w:num w:numId="3"><w:abstractNumId w:val="0"/><w:lvlOverride w:ilvl="0"><w:startOverride w:val="5"/></w:lvlOverride></w:num>
  <w:num w:numId="4"><w:abstractNumId w:val="4"/></w:num>
  <w:num w:numId="7"><w:abstractNumId w:val="0"/></w:num>
  <w:num w:numId="5"><w:abstractNumId w:val="2"/></w:num>
  <w:num w:numId="6"><w:abstractNumId w:val="3"/></w:num>
</w:numbering>`;
const membership: (readonly [number, number] | null)[] = [
  null,
  [1, 0],
  [1, 1],
  null,
  [1, 1],
  [1, 0],
  [1, 1],
  [2, 0],
  [2, 1],
  [2, 0],
  [3, 0],
  [3, 0],
  [4, 0],
  null,
  null,
  [5, 0],
  [5, 0],
  [6, 0],
];
const paragraphs = child(pkg.xml(pkg.mainPart), 'body')!.children.filter((n) => isWord(n, 'p'));
const patches = paragraphs.map((p, i) => {
  const old = child(p, 'pPr'),
    list = membership[i];
  const style = i === 13 ? '<w:pStyle w:val="Quote"/>' : '';
  const num = list
    ? `<w:numPr><w:ilvl w:val="${list[1]}"/><w:numId w:val="${list[0]}"/></w:numPr>`
    : '';
  const indent =
    i === 13
      ? '<w:ind w:firstLine="360"/>'
      : i === 14
        ? '<w:ind w:left="720" w:hanging="360"/>'
        : '';
  return {
    start: old?.start ?? p.openEnd,
    end: old?.end ?? p.openEnd,
    replacement: `<w:pPr>${style}${num}${indent}</w:pPr>`,
  };
});
const styles = pkg.xml('word/styles.xml');
const quote =
  '<w:style w:type="paragraph" w:styleId="Quote"><w:name w:val="Quote"/><w:basedOn w:val="Normal"/><w:pPr><w:ind w:left="720" w:right="720"/></w:pPr></w:style>';
const updated = pkg.withXml(
  new Map([
    [pkg.mainPart, patchXml(pkg.text(pkg.mainPart), patches)],
    ['word/numbering.xml', numbering],
    [
      'word/styles.xml',
      patchXml(pkg.text('word/styles.xml'), [
        { start: styles.closeStart, end: styles.closeStart, replacement: quote },
      ]),
    ],
  ]),
);
await writeFile(path, updated.save());
console.log('Added bullet, override, indentation and alphabetic variants to lists.docx');
